<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>proto</string>
	</array>
	<key>name</key>
	<string>Protocol Buffer</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storagetypes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#enum</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#message</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#option</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#oneof</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#packaging</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#service</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
			<key>name</key>
			<string>constant.numeric.proto</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.proto</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.proto</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>match</key>
			<string>\b(true|false|max)\b</string>
			<key>name</key>
			<string>constant.language.proto</string>
		</dict>
		<key>enum</key>
		<dict>
			<key>begin</key>
			<string>(enum)(\s+)([A-Za-z][A-Za-z0-9_]*)(\s*)(\{)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.proto</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.proto</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#option</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(to|extensions)\b</string>
					<key>name</key>
					<string>keyword.source.proto</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.proto</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.proto</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([A-Za-z][A-Za-z0-9_]*)(\s*)(=)(\s*)([0-9]*)</string>
				</dict>
			</array>
		</dict>
		<key>message</key>
		<dict>
			<key>begin</key>
			<string>(message|extend)(\s+)([A-Za-z][A-Za-z0-9_.]*)(\s*)(\{)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.proto</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.message.proto</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#enum</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#option</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#oneof</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(optional|repeated|required|to|extensions)(\s+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.source.proto</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#storagetypes</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.class.proto</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([A-Za-z][A-Za-z0-9_]*)(\s+)([A-Za-z][A-Za-z0-9_]*)</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.proto</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(\s*)(=)(\s*)([0-9]*)</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\[</string>
							<key>end</key>
							<string>\]</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>default|packed|deprecated|lazy</string>
									<key>name</key>
									<string>keyword.source.proto</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#constants</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>oneof</key>
		<dict>
			<key>begin</key>
			<string>(oneof)(\s+)([A-Za-z][A-Za-z0-9_]*)(\s*)(\{)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.proto</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#option</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(to|extensions)\b</string>
					<key>name</key>
					<string>keyword.source.proto</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.proto</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.proto</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([A-Za-z][A-Za-z0-9_]*)(\s+)([A-Za-z][A-Za-z0-9_]*)(\s*)(=)(\s*)([0-9]*)</string>
				</dict>
			</array>
		</dict>
		<key>option</key>
		<dict>
			<key>begin</key>
			<string>(\b)(option)(\b)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.source.proto</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>match</key>
					<string>default|packed|optimize\_for|java\_package|java\_outer\_classname|go\_package|deprecated|lazy|\w+\_api\_version</string>
					<key>name</key>
					<string>storage.type.proto</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(CODE\_SIZE|SPEED)</string>
					<key>name</key>
					<string>constant.language.proto</string>
				</dict>
			</array>
		</dict>
		<key>packaging</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.proto</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(package|import)(?=(\s+)(["]?[A-Za-z][A-Za-z0-9-_./]*["]?)(;))</string>
		</dict>
		<key>service</key>
		<dict>
			<key>begin</key>
			<string>(service)(\s+)([A-Za-z][A-Za-z0-9_.]*)(\s*)(\{)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.proto</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.message.proto</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(rpc)(\s+)([A-Za-z][A-Z-a-z0-9_]+)(\s*)(\([A-Za-z0-9_]+\))(\s+)(returns)(\s+)(\([A-Za-z0-9_]+\))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.source.proto</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>keyword.source.proto</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
				</dict>
			</array>
		</dict>
		<key>storagetypes</key>
		<dict>
			<key>match</key>
			<string>\b(double|float|int32|int64|uint32|uint64|sint32|sint64|fixed32|fixed64|sfixed32|sfixed64|bool|string|bytes)\b</string>
			<key>name</key>
			<string>storage.type.proto</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.proto</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.proto</string>
	<key>uuid</key>
	<string>750ac1f3-b172-48de-b1a4-a3c310c4a293</string>
</dict>
</plist>
